apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
  labels:
    app: {{ .Release.Name }}-postgres
data:
  POSTGRES_DB: {{ .Values.global.db.dbname }}
  POSTGRES_USER: {{ .Values.global.db.dbuser }}
  POSTGRES_PASSWORD: # use derivePassword
