apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  type: NodePort
  ports:
   - port: 6379
  selector:
   app: {{ .Release.Name }}-redis
