apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx
          image: quay.io/vanessa/sregistry_nginx:latest
          env:
           {{- range $name,$val := .Values.env }}
           - name: {{ $name }}
             value: {{ $val | quote }}
           {{- end }}
           - name: DB_HOST
             value: {{ (printf "%s-postgres" .Release.Name) | quote }}
           - name: DB_NAME
             value: {{ .Values.global.db.dbname | quote }}
           - name: DB_USER
             value: {{ .Values.global.db.dbuser | quote }}
           - name: DB_PASSWORD
             value: # use derivePassword
           - name: REDIS_URL
             value: {{ (printf "redis://%s-redis/0" .Release.Name) | quote }}
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: def-config
              subPath: default.conf
            - mountPath: /etc/nginx/uwsgi_params.par
              name: uwsgi-param
              subPath: uwsgi_params.par
            - mountPath: /etc/ssl/certs
              name: certs
            - mountPath: /etc/ssl/private
              name: keys
            - mountPath: /code
              name: code
            - mountPath: /var/www/static
              name: static
            - mountPath: /var/www/images
              name: images
      volumes:
        - name: certs
          hostPath:
            path: {{ .Values.global.path.certs }}
            type: Directory
        - name: keys
          hostPath:
            path: {{ .Values.global.path.keys }}
            type: Directory
        - name: def-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
            items:
            - key: nginx
              path: default.conf
        - name: uwsgi-param
          configMap:
            name: {{ .Release.Name }}-uwsgi-params
            items:
            - key: uwsgi
              path: uwsgi_params.par
        - name: code
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-uwsgi-code-pv-claim
        - name: static
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-uwsgi-static-pv-claim
        - name: images
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-uwsgi-images-pv-claim
