apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-uwsgi
  labels:
    app: {{ .Release.Name }}-uwsgi
spec:
  type: ClusterIP
  ports:
   - name: uwsgi
     protocol: TCP
     port: 3031
  selector:
   app: {{ .Release.Name }}-uwsgi
