apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/client-max-body-size: "8000m"
    nginx.ingress.kubernetes.io/proxy-body-size: "8000m"
  name: {{ .Release.Name }}-registry-ingress
spec:
  rules:
    - host: {{ .Values.global.registryDNS }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-nginx
              servicePort: 80
            path: /
  tls:
  - hosts:
      - {{ .Values.global.registryDNS }}
    secretName: {{ .Release.Name }}-registry-tls
