apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx: |- 
    {{- $relname := .Release.Name }}
    {{- range $line := .Files.Lines "nginx.conf" }}
    {{ $line | replace "uwsgi-svc"  (printf "%s-uwsgi" $relname) }}
    {{- end }}
